# Creation Date: 4/19/2024
#
# Author: Nathan Wren
---

# file : main.yml

- hosts: localhost
  gather_facts: yes
  become: no

  tasks:
    - name: Configure shell
      import_role:
        name: shell
    - name: Configure Vim
      import_role:
        name: vim
    - name: Configure VSCode
      import_role:
        name: vscode
    - name: Configure Containerization tools
      import_role:
        name: container_tools
