---
# tasks file for vscode
- name: Import MS GPG Key
  ansible.builtin.rpm_key:
    key: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  become: yes
  notify:
    - DNF update

- name: Ensure repo present
  ansible.builtin.copy:
    src: "{{ vscode_repo }}"
    dest: "{{ yum_repos }}/{{ vscode_repo }}"
  become: yes
  notify:
    - DNF update

- name: Install code
  ansible.builtin.dnf:
    name: code
    state: present
  become: yes
